
name : "Prototype Test Suite"
description : "Prototype Test Suite (for functional testing purposes only)"

pathloc:
    testSuitePath: "D:\Documentos de usuario\Admin\PrototypeTestSuite\config"
    testSuitePath: prototypeModule
    testSuiteClass: PrototypeClass

sutConfig: "D:\Documentos de usuario\Admin\PrototypeTestSuite\config\sut.config.yml"

testCasesList:
    - "D:\Documentos de usuario\Admin\PrototypeTestSuite\test\test1.yml"


logLevel: DEBUG
