cosmos::slave::netmask: "255.255.255.0"
cosmos::slave::host_key_pub_file: "puppet:///modules/cosmos/environments/%{environment}/%{hostname}_key"
slave_hosts:
    - "compute1"
    - "compute2"
    - "store1"
    - "store2"