#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

ambari::params::repo_url: %{cosmos::params::cosmos_repo_platform_url}
cosmos::params::cosmos_subnet: '192.168.63.0'
cosmos::params::cosmos_netmask: '255.255.255.128'
cosmos::params::cosmos_repo_platform_url: 'http://cosmos10.hi.inet/nexus/service/local/yum/repos/snapshots/staging'
cosmos::params::cosmos_ssl_cert_source: "puppet:///modules/cosmos/environments/%{environment}/certs/%{hostname}_cer.pem"
cosmos::params::cosmos_ssl_key_source: "puppet:///modules/cosmos/environments/%{environment}/certs/%{hostname}_key.pem"
cosmos::slave::gateway: "192.168.63.1"
cosmos::slave::ct_gateway: "192.168.63.1"
cosmos::slave::host_key_priv_file: "puppet:///modules/cosmos/environments/%{environment}/%{hostname}_key"
cosmos::slave::ct_key_priv_file: "puppet:///modules/cosmos/environments/%{environment}/%{hostname}_ct_key"
cosmos::params::domain: '.hi.inet'
cosmos::params::master_ip: '192.168.63.11'
cosmos::params::master_hostname: 'andromeda01'
cosmos::params::infinity_url: 'hdfs://andromeda-infinity.hi.inet'
cosmos::params::pdihub_client_id: '20f0381a6698c19953d5'
cosmos::params::pdihub_client_secret: 'b11b73f83e7dcf940fec3356d3d0604e3169ab98'
cosmos::params::horizon_password: 'horizon!'
cosmos::params::ambari_yarn_total_memory: 28672
cosmos::params::ambari_yarn_container_min_memory: 3584
cosmos::params::ambari_yarn_virtual_physical_memory_ratio: 2.1
cosmos::params::ambari_map_task_memory: 3584
cosmos::params::ambari_reduce_task_memory: 3584
cosmos::params::ambari_map_heap_memory: 2048
cosmos::params::ambari_reduce_heap_memory: 2048
cosmos::params::ambari_mr_app_master_memory: 1024
cosmos::openvz::network::host_iface: 'bond0.1'
slave_hosts:
    - 'andromeda02'
    - 'andromeda03'
    - 'andromeda04'
    - 'andromeda05'
    - 'andromeda06'
    - 'andromeda07'
    - 'andromeda08'
    - 'andromeda99'
