#)
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::ip: "192.168.63.47"
cosmos::slave::ct_ip: "192.168.63.111"
cosmos::slave::ct_hostname: "orion-compute25"
cosmos::slave::hardware_profile: g1-compute
cosmos::slave::name: "Orion 25"
cosmos::slave::ram: 32768
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDc6oaAjnwrP9oUcfjMw/DoWO0LNOmpwHskVpRc2kczQPWPDPLuoBv8Gz2OWq91NhLX9pD3bcEv24RQh+zD8EgGKka7De7ci9s5DkI4mWGGn/LKCj861pKg6V2XCAgteZq+LADhkXyD7umlXFrlWpiDo+RGvwwxrhPmCgOEqxpBbLLf/2GLxlfLcGVo1B9xCvElDc73S8v0izdqOk6UZzoQkaDqbS1jMy/Q9cURSBod4TDYVViUB7Pnp8cjM2HPGiQnHgEUIAlYEjvH2Z7+pO9ypKA+UbkTnYfuP18lymZ5lc9L0J42HtCKzY0Y8aYNnNI7hBNuRWNSNJNJRh5bstQB"
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDM2Ou3otVJhGcFNp2V2O8PdAKMcmdfGKMiKe3TTCkNZle60aHILCmkioD3uYcL4C2yAeKtK7Hwrt6IJaDp/wUqEjKnoDvhAWtJcxFoUwi+dVEa+H80AnSSLIUD76zkgPoHTJwmgE0dQY/xkQiwXWqg1S1E5gvufrv5vQfxuQv+c7iaeLAfzU5RdquaAn6fPnJI2q+yWBG34yj76VTNGPFl7zZj/joSI3nAL1XJY+RzQmBpwSS7J4kW9TJLTfWCGeL7FXD4cQ0lDOCr+e/awwKc6I9U7+Cv2l3S8v8zAczVwszmY2i2QAQgYuIhDuztOyxJi7PrSOy06IeAKKPloAZX"
