#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::ip: "192.168.63.26"
cosmos::slave::ct_ip: "192.168.63.90"
cosmos::slave::ct_hostname: "orion-compute08"
cosmos::slave::hardware_profile: 1
cosmos::slave::name: "Orion 08"
cosmos::slave::ram: 32768
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA3sFoGn8O5aCeUv9J88vNrawDxdy6Lt6kQkUTBLwLE9zhnWzHfMLrYvzKptC6joMnX/RoemZnllrFL/HG4tD+D7NvVecMXTf+0VkSqzf0//yawG7PTx9sIufvU6d8+/MJzDBg4U2qnnrvAZAYniJCvQnXowjkosgCCjpQwoz/SA5MM6QmHoDHLUTnX9zsCDZgC3OictpRyFwv63VMqiib4KmmsJg3nNPQ0QMT8n/6VmC/zaOj+/gS4TIDcuVNSyolPsmKFQGiKMW6Ig+eBfpngL1TnPQXNqnzfja8XJ9j34Pj9L09TPMjYsaeIPFEQksjfVLetSi1/7HOyp1HSCPzQw=="
